# Generated by Django 2.0.3 on 2020-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chengji',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
