# Generated by Django 2.0.3 on 2020-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0003_auto_20200918_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peroninfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
