# Generated by Django 2.0.3 on 2020-09-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0004_auto_20200918_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peroninfo',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
