# Generated by Django 2.0.3 on 2020-09-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0005_auto_20200919_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='chengji',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chengji',
            name='no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chengji',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chengji',
            name='updata_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='peroninfo',
            name='name',
            field=models.CharField(blank=True, default='默认值', max_length=30, null=True),
        ),
    ]
