# Generated by Django 2.0.3 on 2020-09-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0006_auto_20200919_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='peroninfo',
            name='qq',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
